src/Entity/Recipes.php
<?php

namespace App\Entity;

use App\Repository\RecipesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RecipesRepository::class)]
class Recipes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $Name = null;

    #[ORM\ManyToMany(targetEntity: Ingredients::class, inversedBy: 'recipes')]
    private Collection $ingredients;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img_url = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $description = null;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->Name;
    }
    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection<int, Ingredients>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredients $ingredient): static
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(Ingredients $ingredient): static
    {
        $this->ingredients->removeElement($ingredient);

        return $this;
    }

    public function getImgUrl(): ?string
    {
        return $this->img_url;
    }

    public function setImgUrl(?string $img_url): static
    {
        $this->img_url = $img_url;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/RecipesType.php
<?php

namespace App\Form;

use App\Entity\Ingredients;
use App\Entity\Recipes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name',TextType::class, [
                'label'=> 'Titre de la recette',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('ingredients', EntityType::class, [
                'label'=> 'Ingredients :',
                'class' => Ingredients::class,
                'multiple' => true,
                'expanded' => true,

            ])
            ->add('img_url',TextType::class, [
                'label'=> 'Lien de la miniature de la recette: ',
                'attr' => [
                    'class' => 'form-control',
                ]
            ])
            ->add('description', TextareaType::class,[
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipes::class,
        ]);
    }
}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Recipes;
use App\Form\RecipesType;
use App\Repository\RecipesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/recipes')]
class RecipesController extends AbstractController
{
    #[Route('/', name: 'app_recipes_index', methods: ['GET'])]
    public function index(RecipesRepository $recipesRepository): Response
    {
        return $this->render('recipes/index.html.twig', [
            'recipes' => $recipesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_recipes_new', methods: ['GET', 'POST'])]
    #[IsGranted(new Expression('is_granted("ROLE_ADMIN") or is_granted("ROLE_MODERATOR") or is_granted("ROLE_USER")'))]
    public function new(Request $request, RecipesRepository $recipesRepository): Response
    {
        $recipe = new Recipes();
        $form = $this->createForm(RecipesType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipesRepository->save($recipe, true);

            return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipes/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recipes_show', methods: ['GET'])]
    public function show(Recipes $recipe): Response
    {
        return $this->render('recipes/show.html.twig', [
            'recipe' => $recipe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recipes_edit', methods: ['GET', 'POST'])]
    #[IsGranted(new Expression('is_granted("ROLE_ADMIN") or is_granted("ROLE_MODERATOR") or is_granted("ROLE_USER")'))]
    public function edit(Request $request, Recipes $recipe, RecipesRepository $recipesRepository): Response
    {
        $form = $this->createForm(RecipesType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipesRepository->save($recipe, true);

            return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipes/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recipes_delete', methods: ['POST'])]
    #[IsGranted(new Expression('is_granted("ROLE_ADMIN")'))]
    public function delete(Request $request, Recipes $recipe, RecipesRepository $recipesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $recipesRepository->remove($recipe, true);
        }

        return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recipes/_delete_form.html.twig
{% if is_granted('ROLE_MODERATOR') or is_granted('ROLE_ADMIN') %}
    <form method="post" action="{{ path('app_recipes_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette recette ?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
        <button class="btn mt-3" style=" box-shadow: 0px 0px 15px lightgray;">Supprimer la recette</button>
    </form>
{% endif %}

templates/recipes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-3">{{ button_label|default('Ajouter la recette') }}</button>
{{ form_end(form) }}

templates/recipes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la recette{% endblock %}

{% block body %}
<main>
    <div class="content px-4">
        <a href="{{ path('app_recipes_index') }}">Retour à la liste des recettes</a>
        <div class="form mt-3">
            <h1>Modification de la recette</h1>
            {{ include('recipes/_form.html.twig', {'button_label': 'Confirmer'}) }}
            {{ include('recipes/_delete_form.html.twig') }}
        </div>
    </div>
</main>
{% endblock %}

templates/recipes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Toutes nos recettes{% endblock %}

{% block body %}
	<main>
		<div class="content p-4">
			<h1>Liste des recettes</h1>
			{% if app.user %}
				<div class="addRecipe-btn mb-3 btn btn-light">
					<a href="{{ path('app_recipes_new') }}">Ajouter une recette</a>
				</div>
			{% endif %}
			<div class="cards mt-3">
				{% for recipe in recipes %}
					<div class="card" style="--bs-card-border-width: none">
						<img src="{{ recipe.imgUrl }}" class="card-img" alt="Miniature">
						<div class="card-img-overlay">
							<h5 class="card-title">{{ recipe.Name }}</h5>
							<a href="{{ path('app_recipes_show', {'id': recipe.id}) }}">
								<button class="btn btn-primary px-4">Voir</button>
							</a>
						</div>
					</div>
					{% else %}
					<div>
						<p>Aucunes recettes n'as été trouvées !</p>
					</div>
				{% endfor %}
			</div>
		</div>
	</main>
{% endblock %}

templates/recipes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une recette{% endblock %}

{% block body %}
<main>    
    <div class="content px-4">
        <a href="{{ path('app_recipes_index') }}">Retour aux recettes</a>
        <div class="form mt-3">
            <h1>Ajoutez une nouvelle recette</h1>

            {{ include('recipes/_form.html.twig') }}
        </div>
    </div>
</main>
  

{% endblock %}

templates/recipes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recette du : {{recipe.Name}} {% endblock %}

{% block body %}
<main>
    <div class="content p-4">
        <a href="{{ path('app_recipes_index') }}">Retour aux recettes</a>
        <h1 class="mt-4 mb-3">Recette : {{recipe.Name}}</h1>
        <div class="recipeShow">
            <div class="recipeImg mb-4">
                <img class="rounded" src="{{recipe.imgUrl}}" alt="image">
            </div>
            <div class="recipeInfo">
                <div>
                    <h1>Voici les étapes de la recette a suivre : </h1>
                    <p>{{recipe.description}}</p>
                </div>
                <h3>Liste des ingrédients nécéssaires: </h3>
                <div>
                    {% for ingredient in recipe.ingredients %}
                        <ul>
                            <p> -{{ingredient.name}}</p>
                        </ul>
                    {% endfor %}
                    <div class="recipeBtn">
                        <a class="btn btn-primary" href="{{ path('app_recipes_edit', {'id': recipe.id}) }}">Modifier</a>
                        {{ include('recipes/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}